### ISSUE TITLE
settings.php missing

### ISSUE THREAD

**Issue by andreasbrett** [michaelzangl/wp-video-embed-privacy#1]
The preview picture feature is not working. It's giving me "wrong key". Looking into preview.php I see that a settings.php file is invoked which I don't seem to find in your repository. Looks like preview.php can't fetch the key that it needs to re-calculate the sha256 hash for comparing it to the provided "$s" parameter.

**Comment by andreasbrett** [comment]
Never mind.... The settings.php could not be written due missing permissions on the previews folder. I had to chown the plugin folder as I uploaded with a different one. Maybe you could fetch missing write permissions.

**Comment by mundschenk-at** [comment]
Caching data should live in a sub-folder of the `uploads` directory - plugin and theme folders are not guaranteed to be writable. Use [`wp_get_upload_dir()`](https://developer.wordpress.org/reference/functions/wp_get_upload_dir/) to retrieve the base directory and create a custom folder using `wp_mkdir_p()`.

**Comment by michaelzangl** [comment]
The problem with that is, that the path from the uploads directory to the plugin directory cannot be determined by a static .htaccess file. If the cache fails, I need the htaccess-File to fall back to the regular file.

I would prefer to simply do all requests in PHP. This is not a problem on powerful servers, but 1und1 and other providers have really poor PHP performance and fetchin a file through the PHP interpreter is much slower than fetching it directly.

**Comment by mundschenk-at** [comment]
You can work around that by registering a rewrite rule and regenerating the cache if the file does not exist, like [here](https://github.com/mundschenk-at/avatar-privacy/blob/master/includes/avatar-privacy/components/class-images.php#L181).

**Comment by michaelzangl** [comment]
The problem with that approach is that uncached images (for people that want to disable this feature that is all images) will then require wordpress to be loaded. While this allows the HTTP library of WP to be used, this is a huge overhead.

**Comment by tyrann0us** [comment]
@michaelzangl, any news on that? IMHO, bootstrapping WordPress to load an image is justifiable, because most users will have some kind of static content caching enabled.

Also, as @mundschenk-at stated, storing files inside the plugin is a real no-go. For security reasons, the only writable path should be `wp-content/`.

Please reconsider this. Thanks!

**Comment by michaelzangl** [comment]
@tyrann0us 
I wrote this plugin for a very low-power Wordpress installed on a shared hosting - what you can do there is limited and there is no content caching in front of it. For pages with a cache infrastructure, I did never maintain a project that uses Wordpress - as soon as you get bigger, you want to use something that scales well and is more custom-built.

Changing the plugin to generate previews on the fly should not be hard. Or just leave out the automated preview and supply a custom image every time. I have also seen several other plugins that solve this problem, since GPDR has gained such high awareness in the last years. This plugin was written before GPDR existed to comply with the old German data protection laws that basically had the same requirements.

So short: No, I won't change the way the plugin works for now, but feel free to fix.
