### ISSUE TITLE
works great - but looks ugly

### ISSUE THREAD

**Issue by fgoellner** [michaelzangl/wp-video-embed-privacy#7]
Hi,
am trying to adjust several sites to DSGVO compliance. This plugin solution for youtube embeds works great for me. But according to my taste it looks awful. And sad to say to my clients taste, too. 
http://jugendkonzertchor.de/media/#video-produktionen
Isn't it possible to set up my own pic to use as place marker? I don't want this ugly one from a server. And isn't it possible to have some sort of window with explanations? Have a look at this solution for elementor: https://heddesheimer.de/blog/youtube-videos-datenschutzkonform-einbinden-dsgvo/
There is no way to turn that message off, but it is displayed so much nicer. 
In my case I'll try to improve this plugin a bit by css, but I would appreciate a lot to use a pic I generate myself. Will you work on an update?

**Comment by michaelzangl** [comment]
Thanks for posting the link.

The problem is with the CSS introduced by `cmsms_video_wrap`. Please see what plugin / theme is interfering with video embedding and try to resolve the issue with your theme author.

The idea of the video is to make everything automatic. You can fix your Youtube preview images on the Youtube site by selecting an other image in the "creator studio".
